FROM node

# Install Build Essentials
RUN apt update && apt install sudo git curl wget zip unzip build-essential file apt-utils jq -y
# Installing cert package will allow resolving the error to https://registry.npmjs.org/
RUN apt install ca-certificates

# non-root
ENV USER=quasar
ENV HOME=/home/$USER
RUN adduser --disabled-password --gecos "" --shell /bin/bash $USER --home $HOME
RUN adduser $USER sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER $USER
WORKDIR $HOME/workdir

# bash as default
SHELL ["/bin/bash", "-c"]

# cordova
ARG NPM_VERSION=latest
ARG CORDOVA_VERSION=latest
ARG QUASAR_CLI_VERSION=latest
RUN sudo npm install -g npm@$NPM_VERSION && \
    sudo npm install -g cordova@$CORDOVA_VERSION && \
    sudo npm install -g @quasar/cli@$QUASAR_CLI_VERSION

# sdkman
RUN curl -s "https://get.sdkman.io" | bash
ENV SDKMAN_HOME=$HOME/.sdkman
ARG JAVA_VERSION=17.0.8-amzn
ARG GRADLE_VERSION=7.6

# java/gradle
RUN source "$SDKMAN_HOME/bin/sdkman-init.sh" && sdk install java $JAVA_VERSION && sdk install gradle $GRADLE_VERSION
ENV JAVA_HOME=$SDKMAN_HOME/candidates/java/current
ENV GRADLE_HOME=$SDKMAN_HOME/candidates/gradle/current

# https://en.wikipedia.org/wiki/Android_version_history
ENV SDK_URL="https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip" \
    ANDROID_HOME="$HOME/android/sdk" \
    ANDROID_SDK_ROOT="$HOME/android/sdk" \
    # ANDROID_VERSION=27 \
    # ANDROID_BUILD_TOOLS_VERSION=27.0.3
    ANDROID_VERSION=33 \
    ANDROID_BUILD_TOOLS_VERSION=33.0.2

ARG ANDROID_SDK_VERSION=9477386
RUN mkdir -p $ANDROID_HOME/cmdline-tools && \
    wget https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_VERSION}_latest.zip && \
    unzip *tools*linux*.zip -d $ANDROID_HOME/cmdline-tools && \
    mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/tools && \
    rm *tools*linux*.zip

# Env
ENV ANDROID_BUILD_TOOLS_HOME=$ANDROID_HOME/build-tools/$ANDROID_BUILD_TOOLS_VERSION
ENV PATH=$PATH:$ANDROID_BUILD_TOOLS_HOME:$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools:$ANDROID_HOME/cmdline-tools/tools/bin
ENV PATH=$PATH:$GRADLE_HOME/bin:$JAVA_HOME/bin
# WORKAROUND: for issue https://issuetracker.google.com/issues/37137213
ENV LD_LIBRARY_PATH=$ANDROID_HOME/emulator/lib64:$ANDROID_HOME/emulator/lib64/qt/lib

# Download Android SDK
RUN mkdir -p "$ANDROID_HOME" $HOME/.android \
    && touch $HOME/.android/repositories.cfg \
    && cd "$ANDROID_HOME" \
    && curl -o sdk.zip $SDK_URL \
    && unzip sdk.zip \
    && rm sdk.zip \
    && mkdir "$ANDROID_HOME/licenses" || true \
    && yes | sdkmanager --licenses

# Install Android Build Tool and Libraries
RUN sdkmanager --update
RUN sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION" \
    "platforms;android-$ANDROID_VERSION" \
    "platform-tools"
