name: Deploy APK to GitHub Pages
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Deploy APK"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'src-cordova'
      - name: set git config
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git config -l
      - name: Deploy
        run: |
          docker run -e QENV=local \
          -v $(pwd):/tmp/src-cordova \
          -w /tmp/src-cordova \
          hldtux/quasar-apk bash -c "pwd && ls -lha && npm run build-apk"
